  - title: Ardan Labs
    url: https://www.ardanlabs.com/
    thumbnail:
    blurb: 提供定制化的现场授课培训。
  - title: Gopher Guides
    url: https://www.gopherguides.com/
    thumbnail:
    blurb: 提供定制化的面授、远程及在线培训，由开发者面向开发者授课。
  - title: Boss Sauce Creative
    url: https://bosssauce.it/services/training
    thumbnail:
    blurb: 为团队提供个性化或按学习路线组织的 Go 培训。
  - title: Shiju Varghese
    url: https://github.com/shijuvar/gokit/tree/master/training
    thumbnail:
    blurb: 在印度提供 Go 线下课堂培训及分布式系统架构咨询。
  - title: kkoehler
    url: https://golang.kkoehler.com/
    thumbnail:
    blurb: 在德国、奥地利和瑞士提供 Go 面授培训。
